### ISSUE TITLE
System.MissingMethodException' in Dapper.dll

### ISSUE THREAD

**Issue by decay29** [DapperLib/Dapper#1103]
I have a UWP project that works fine in debug mode (x64, x86), but when trying to run it in Release Mode, it crashes on the first query with this

```
Exception thrown: 'System.MissingMethodException' in Dapper.dll
An exception of type 'System.MissingMethodException' occurred in Dapper.dll but was not handled in user code
Method 'DynamicMethod..ctor(string, Type, Type[])' from assembly 'System.Reflection.Emit.Lightweight' was not included in compilation, but was referenced in CommandDefinition.GetInit(Type). There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

```
I am using 1.50.5 and NetCore.UniversalWindowsPlatform 2.1.0.  My target is 1803, and Min Version is Fall Creators Update

Thanks

**Comment by mgravell** [comment]
Dapper is reflection-heavy. It may not work at all on pruned runtimes like
UWP. There may be a way of telling it not to prune the lib. I don't know.
This sounds like a UWP issue more than anything, but: that is outside of my
expertise.

**Comment by NickCraver** [comment]
There's nothing to do on this one as-is, but keep an eye out for the work in https://github.com/DapperLib/DapperAOT which may end up suiting some of these use cases as we try a move to generators instead of IL overall. There aren't assurances all platforms support the methods needed yet, but it should improve things!
