### ISSUE TITLE
Add support for constructor with less params than columns in the query

### ISSUE THREAD

**Issue by alex-jitbit** [DapperLib/Dapper#1384]
Hope I'm making myself clear, Something like this:

```
public class MyObject
{
	public int Column1 {get;set;}
	public int Column2 {get;set;}
	public int Column3 {get;set;}

	public MyObject(int Column1)
	{
		this.Column1 = Column1;
	}
}
```

Currently this will throw an exception `A parameterless default constructor or one matching signature (System.Int32 Column1, System.Int32 Column2, System.Int32 Column3) is required`

I could try to work on a pull request and propose a change for the `FindConstructor` method. Just wanted to know what you guys think about this and if it fits your current.. uhm.. ideology.

**Comment by brianpursley** [comment]
I think this is because serializations needs a parameterless constructor in order to work.

Can you just do something like this?

```
public class MyObject
{
	public int Column1 {get;set;}
	public int Column2 {get;set;}
	public int Column3 {get;set;}

	public MyObject()
        {
        }

	public MyObject(int Column1)
	{
		this.Column1 = Column1;
	}
}
```

**Comment by alex-jitbit** [comment]
This totally ruins the point as the constructor won't be called.

I need to Dapper to use my constructor

**Comment by brianpursley** [comment]
No it does not "totally ruin the point".

You never said you needed Dapper to call your single argument constructor, only that it was throwing an exception, and I suggested a way to avoid the exception.  Without having enough details, I assumed your use of the single parameter constructor was for object creation in your code, outside of Dapper.

Well, anyway, I'm not a spokesperson for the Dapper project, so I will let someone else reply as to whether it fits the ideology.

Best of luck with your project!

**Comment by NickCraver** [comment]
I'm not sure doing this would be a good idea, since what's called would be very "fuzzy" (and more expensive, though we could minimize that). Right now we look for _exactly_ that constructor and you can reason about _exactly_ what we're looking for. If it looked for any number of lesser parameters down the chain, which one do we choose? Do we look for `n`, then `n-1`, `n-2`, etc.? What if types on them are convertible where `n` _might_ be okay but `n-1` types match exactly? Do we call the constructor with the `n` match found then...set the remaining properties? or discard them?

The above line of thinking are the behavior questions off the top of my head. Given how complex it gets, I'd counter the proposal here with: why not select the columns you want to match your current constructor?

Alternatively, there are other ways to do this with a multi-match query as well, with a `splitOn` of `Column2` and such. Here's an example of that alternative:
```cs
void Main()
{
	using (var conn = new SqlConnection("Data Source=.;Integrated Security=True"))
	{
		conn.Query<MyObject, int, int, MyObject>("Select 10 Column1, 20 as Column2, 30 as Column3",
		(obj, col2, col3) =>
		{
			obj.Column2 = col2;
			obj.Column3 = col3;
			return obj;
		}, splitOn:"Column2,Column3").Dump();
	}
}

public class MyObject
{
	public bool HitConsructor { get; set;}
	public int Column1 { get; set; }
	public int Column2 { get; set; }
	public int Column3 { get; set; }

	public MyObject(int Column1)
	{
		this.Column1 = Column1;
		HitConsructor = true;
	}
}
```
Which results in:
![image](https://user-images.githubusercontent.com/454813/80924792-009b3980-8d59-11ea-811c-216d8de51627.png)

**Comment by asartem** [comment]
@NickCraver, @alex-jitbit  is right. The constructor is the only place where entity should be checked and guaranteed to be full or never created.
A very common DDD scenarios is to select single table and aggregate some columns of the row :
`Select id, name, price, weight, length, height, width from products:`

into two Entities: Product and Product Dimensions

```
public class Product
{
   public int Id {get; private set;}
   public string Name {get; private set;}
   public decimal Price {get; private set;} 

   ProductDimensions Dimensions {get; private set;}
   
   Product(int id, string name, ProductDimensions dimensions )  // no need Price here
    {  
      if(id < 1) throw new ArgumentException(nameof(id)) // the single place of check
      Id= id;  
    }

    Product(int id, string name, decimal price, ProductDimensions dimensions ) : this(id, name, dimensions)
    {  
      if(price< 0) throw new ArgumentException(nameof(price)) // the single place of check
      Price= price;  
    }
}

public class ProductDimensions{
  public decimal Weight {get; private set}
  public decimal Height{get; private set}
  public decimal Lenght {get; private set}
  public decimal Width {get; private set}

   public  ProductDimensions() {}
}

```
I didn't find a good way to implement this basic. 

>  If it looked for any number of lesser parameters down the chain, which one do we choose? 

what about attribute, which marks required constructor? Unfortunately, now the values which come to constructor marked as ExplicitConstructor are zeros. I think this constructor is called without passing values. And the values are still set no via explicit constructor, but via reflection and properties. But constructor is called first and 0 value (of id) will throw the exception.

**Comment by NickCraver** [comment]
The solutions pitch here all have the basic fuzzy problems I mentioned above, so I don't think this is something we can reasonably add. Even if we could make it work, where does it stop? Down to 1 column? That would create a breaking change that would do _very_ different things for consumers. This may not fit the use cases proposed here, but we can't support them without harming _other_ use cases (which are the majority of users).

For now, I suggest either:
1. Changing the query, to drop the columns you don't care about.
2. Create an overloaded constructor, discarding the values you don't care about.

Going to close this one out to cleanup since it's not a path we'll go down in the core lib at least.
