### ISSUE TITLE
Add query support for ExpandoObjects

### ISSUE THREAD

**Issue by MikeADoodleDo** [DapperLib/Dapper#1549]
If you want a collection of ExpandoObjects objects from a dapper query (Syncfusion's Blazor Grid works with ExpandoObjects rather than dynamic for example) you need to do a painful conversion from the dynamic objects to the ExpandoObjects.

**Comment by NickCraver** [comment]
I wish I had a better story for your case, but I can at least confirm your information/approach is correct - no plans to move back to `ExpandoObjects` overall since that has other performance penalties. Custom code is likely your best route here, since Expando wouldn't go back into the library itself.

From an architecture perspective, I recommend using as many concrete types as possible (we're removing `dynamic` from the codebase as much as possible), so as much compile time checking as possible is in play.
