### ISSUE TITLE
Npgsql 6.0.0-rc.1 DateTime issue

### ISSUE THREAD

**Issue by 3ldar** [DapperLib/Dapper#1716]
We are using a library named `Hangfire.PostgreSql` and it uses `Dapper` under the hood. In that library there is a code block like below : 
```
 using (var transaction = connection.BeginTransaction(IsolationLevel.RepeatableRead))
                {
                    int affected = -1;

                    affected = connection.Execute($@"DELETE FROM ""{options.SchemaName}"".""lock"" WHERE ""resource"" = @resource AND ""acquired"" < @timeout",
                        new
                        {
                            resource = resource,
                            timeout = DateTime.UtcNow - options.DistributedLockTimeout
                        });

                    transaction.Commit();
                }
```

DDL that generates the target table is like below :
```
create table hangfire.lock
(
	resource text not null
		constraint lock_resource_key
			unique,
	updatecount integer default 0 not null,
	acquired timestamp with time zone
);
```

If we change `timeout = DateTime.UtcNow - options.DistributedLockTimeout` into this `   timeout = DateTimeOffset.UtcNow - options.DistributedLockTimeout` it works as expected.

In  6.0.0-rc1.0 npgsql there is a breaking change that changes the target type of `DateTime` into `timestamp with time zone`. 
Related [info](https://www.npgsql.org/efcore/release-notes/6.0.html#timestamp-rationalization-and-improvements)

The library uses 2.0.78 version of dapper but I've managed the reproduce the same issue with 2.0.90 version.

**Comment by NickCraver** [comment]
I'm trying to understand what the issue is - as I understand it, it looks like if the behavior has changed, the Hangfire would need to change to match. What would Dapper do differently here?

**Comment by 3ldar** [comment]
> I'm trying to understand what the issue is - as I understand it, it looks like if the behavior has changed, the Hangfire would need to change to match. What would Dapper do differently here?

The issue is when I try to execute the above statement with the same parameter types and values using raw `Npgsql` it doesn't fail. Here is the sample that succeeds
```
var connection = new NpgsqlConnection("cs");
await connection.OpenAsync();
using var transaction = await connection.BeginTransactionAsync(IsolationLevel.RepeatableRead);
 var command = new NpgsqlCommand($@"DELETE FROM ""hangfire"".""lock"" WHERE ""resource"" = @resource AND ""acquired"" < @timeout")
            {
                Connection = connection,
                Transaction = transaction
            };
         
command.Parameters.Add(new NpgsqlParameter("@resource", "abuzer"));
command.Parameters.Add(new NpgsqlParameter("@timeout", DateTime.UtcNow - TimeSpan.FromMinutes(10)));

await command.ExecuteNonQueryAsync();
```

**Comment by rezabay** [comment]
This particular example is for inputs and I know for sure that the passed value is indeed DateTime with UTC kind. Npgsql does not do any conversion anymore and instead picks the corresponding time handler based on "Kind: value: https://github.com/npgsql/npgsql/blob/3d2a0af5c6d994bb2efad3bf6f456603b077d607/src/Npgsql/TypeMapping/BuiltInTypeHandlerResolver.cs#L459. The workaround is to pass DateTimeOffset but I just want to find the root cause of issue before the release date of .Net 6.

**Comment by rezabay** [comment]
Ok, I think I kind of know what is going on. When DbType is set to DbType.DateTime,  Npgsql maps it to NpgsqlDbType.Timestamp (https://github.com/npgsql/npgsql/blob/dba60fb5a87bc6d661bbdcd2a31be687edfc10e9/src/Npgsql/TypeMapping/GlobalTypeMapper.cs#L435) and later in NpgsqlParameter class (https://github.com/npgsql/npgsql/blob/dba60fb5a87bc6d661bbdcd2a31be687edfc10e9/src/Npgsql/NpgsqlParameter.cs#L505), TimestampHanler is selected instead of TimestampZHanlder resulting the issue above. I don't know if this is the expected behaviour or a bug after DateTime breaking changes.

**Comment by roji** [comment]
Hey everyone, I want to do my best to help - Npgsql 6.0 indeed does some pretty serious breaking changes. In case you're not aware, you can set an AppContext compatibility switch to revert to the pre-6.0 behavior.

I can see the issue which @3ldar is describing; Dapper sets the DbType on the parameter to the result of LookupDbType, which returns DbType.DateTime. PostgreSQL has two timestamp types: `timestamp without time zone` (for local/unspecified) and `timestamp with time zone`(for UTC); Npgsql uses DbType.DateTime to refer to the former and DbType.DateTimeOffset to refer to the latter (since there's no datetimeoffset DB type). Maybe DbType.DateTime2 would be a better choice (or in addition), but that's beside the point.

The thing is, in 6.0, we no longer allow UTC timestamps to be written to `timestamp without time zone`, since that's mixing timestamp types (UTC goes to UTC, non-UTC to non-UTC). If DbType were to be unset, Npgsql would simply infer automatically what to do by looking at the DateTime's Kind, but since Dapper sets it explicitly, it just does what it's told...

@mgravell @NickCraver is there a particular reason to set DbType rather than let the driver decide? I'm open to making a change on the Npgsql if absolutely necessary, but would like to understand if Dapper is doing the right thing etc.

**Comment by roji** [comment]
BTW another possibly problematic one is TimeSpan -> DbType.Time... PostgreSQL has an `interval` type (which can be over 1 day), and a `time` type (which is really for time of day). Npgsql maps TimeSpan to interval (since TimeSpan can be more than a day), but DbType.Time maps to `time`... so you're effectively overriding the "natural" provider mapping. BTW luckily .NET now has TimeOnly, which can be cleanly mapped to `time`...

**Comment by mgravell** [comment]
spike started, @roji - should be on MyGet soon, assuming no explosions

**Comment by 3ldar** [comment]
@mgravell  Sadly it works on my version of the code (Where setting DbType is completely omitted).

**Comment by KinNeko-De** [comment]
I have a similar issue with testing Npgsql 6.0.0-rc.2
Dapper version 2.0.90

I have a column with a 'timestamptz' format and I want to add a C# 'DateTime' of Kind 'UTC' into this column.
The DateTime is generated by DateTime.UtcNow.
I have a working example with pgsql 5.x.x

When I insert data to this table using dapper I get the following error message:
'Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.'

As far as I understand, this is also related to the DbType. I think it is currently 'timestamp" for DateTime and Npgsql 6.0 rejects that now.

I have inserts with "copy" without dapper that still work.
The only reason I test this feature is to get a UTC Datetime on select without registering using a specific dapper datetimehandler. Selecting using dapper also works fine for me.
EntityFramework had a similar problem with inserting data. https://github.com/zzzprojects/EntityFramework-Extensions/issues/441

So I will not create another issue for that.

**Comment by 3ldar** [comment]
Thanks, everyone for the effort, happy to close this out.

**Comment by mgravell** [comment]
Build for this went to nuget yesterday, btw.

**Comment by pdevito3** [comment]
> PostgreSQL has two timestamp types: timestamp without time zone (for local/unspecified) and timestamp with time zone(for UTC); Npgsql uses DbType.DateTime to refer to the former and DbType.DateTimeOffset to refer to the latter (since there's no datetimeoffset DB type).

@roji is this flipped? I just ran a migration on a `DateTime` prop and it was scaffolded as 'timestamp with timezone' like so: `last_modified_on = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),`. I got to this issue with my system throwing the original error above about assigning non-UTC to UTC because I was doing `DateTime.Now` instead of `DateTime.UtcNow`. I really like this new enforcement, but just wanted to double check I'm understanding it correctly.

**Comment by roji** [comment]
@pdevito3  the interpretation of DbType changed for the final release, see https://github.com/npgsql/npgsql/issues/4106 for more details; tl;dr:

DbType.DateTime -> timestamp with time zone
DbType.DateTime2 -> timestamp without time zone
DbType.DateTimeOffset -> timestamp with time zone

However, that isn't related to the migration change you're describing above (which I'm assuming is EF Core). EF Core doesn't care about DbType, and Dapper no longer sets DbType for DateTime. In the Npgsql EF Core provider, DateTime now maps to `timestamp with time zone` by default, so you can no longer assign non-UTC DateTime to it (hence DateTime.UtcNow and not DateTime.Now).

**Comment by pdevito3** [comment]
yeah, EF Core thanks. makes sense. sorry for polluting the dapper thread!
