### ISSUE TITLE
Npgsql.PostgresException occurs with .net core 3.1 and Dapper 2.0.123

### ISSUE THREAD

**Issue by hkobayas014** [DapperLib/Dapper#1726]
With .net core 3.1 and Dapper 2.0.123, I am getting exceptions from Npgsql.
With 2.0.90, no exceptions occur.

```
{Npgsql.PostgresException (0x80004005): 42P18: could not determine data type of parameter $2
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlConnector.ReadExpecting[T]()
   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1094
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734
   at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 661
   at dotnet31postgres.Program.Main(String[] args) in C:\Users\test\dotnet31postgres\Program.cs:line 32}
```

Here is the sample code.

```C#
using System;
using Dapper;
using Npgsql;

namespace dotnet31postgres
{
    class Program
    {
        static void Main(string[] args)
        {
            var connString = "Host=localhost;Port=5432;Database=hogedb;userid=hoge;password=hoge;"

            using var conn = new NpgsqlConnection(connString);
            conn.Open();

            string sql = "SELECT timestampcol FROM hogetable where logdatetime = @testvalue1 or @testvalue2 is null";
            DateTime? testvalue1 = DateTime.Now;
            DateTime? testvalue2 = null;
            object para = new { testvalue1, testvalue2 };

            var result = conn.Query(sql, para);
            foreach (var res in result)
            {
                Console.WriteLine(res);
            }
        }
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Npgsql" Version="4.*" />
  </ItemGroup>

</Project>
```

Is this the intended change?
Thank you.

**Comment by mgravell** [comment]
Right; we actually changed this behaviour in recent versions, *specifically because* it broke Npgsql 6. So; my first suggestion is: use Npgsql 6, not Npgsql 3. Is there a specific reason you're using a very old version? I will also defer to @roji a bit here; any recommendations for Npgsql 3 consumers?

**Comment by mgravell** [comment]
ooh, interesting; I wonder if this scenario still impacts Npgsql 6 in the `null` case. That's a very real possibility; again: I'm going to glance in @roji's direction for input.

**Comment by hkobayas014** [comment]
Thanks for reply.
Since this is a sample, I used Npgsql 3. In practice, I use Npgsql.EntityFrameworkCore.PostgreSQL 3.1.18 and Dapper together.

**Comment by roji** [comment]
This indeed still reproduces with Npgsql 6.0 - but although this is annoying, I *think* this is the right behavior.

For context, #1723 made Dapper stop setting DbType.DateTime when sending out DateTime parameter. Now, in the usual case, Npgsql simply looks at the CLR type of the parameter value, and infers the PostgreSQL type from that. When the parameter value is null, the database type cannot be inferred, and Npgsql sends the null as an unknown PostgreSQL type.

This isn't usually a problem, since when PostgreSQL gets a parameter with an unknown type, it infers its type from the context; if you compare `@testvalue2` above to the `logdatetime` column, everything is fine. In fact, if the parameter appears more than once, and just *one* of the appearances allows PG to infer, that's also fine, so the following works:

```sql
SELECT timestampcol FROM hogetable WHERE logdatetime = @testvalue2 OR @testvalue2 IS NULL
```

(so although in the later null check it's not possible to infer the type of `@testvalue2`, in the earlier column comparison it's possible).

The problem with the SQL above is specifically that the query does nothing with `@testvalue2` *except* to check if it's null. That query seems a bit dubious to me - to disable the filtering, you could simply transmit null in `@testvalue2` and test that for null as in the query above. Or just check client-side and not send the WHERE altogether.

In any case, if you really do want this to work, you still have the option of telling PostgreSQL what the type is, in the SQL, as follows:

```sql
string sql = "SELECT timestampcol FROM hogetable WHERE logdatetime = @testvalue1 OR @testvalue2::timestamp IS NULL";
```
(or you can override a Dapper DynamicParameter to explicitly specify DbType if you want)

One more thing... this indeed started failing for DateTime because of #1723, but the same thing would fail with other data types before that change. Dapper happens to set DbType [on a closed list of types it knows about](https://github.com/DapperLib/Dapper/blob/main/Dapper/SqlMapper.cs#L170). If you were to use, say IPAddress (which is supports by Npgsql), you'd hit the same issue; Dapper simply cannot be expected to always setting DbType on all types supported across all databases (what's more, DbType simply doesn't have entries for everything).

Does the above sound reasonable @mgravell @hkobayas014?

**Comment by roji** [comment]
@hkobayas014 it's a good idea to distinguish between Npgsql (the ADO.NET provider) and Npgsql.EntityFrameworkCore.PostgreSQL (the EF Core provider for PostgreSQL, AKA EFCore.PG). Thus, EFCore.PG 3.1.18 [depends on](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/3.1.18) Npgsql 4.1.9.

(and regardless, I'd recommend looking at upgrading to the recently-released 6.0 version of everything when you can)

**Comment by mgravell** [comment]
Seems reasonable to me, @roji  - appreciate the guidance

**Comment by hkobayas014** [comment]
@roji 
Thanks for the reply and the detailed explanation!

As a background, my application needs to support both Postgresql and SQL Server, and I don't want to write postgres-only SQL like `@testvalue2::timestamp` for example, so I would like to consider what to do.

By the way, the sample SQL that roji wrote works fine.
```
SELECT timestampcol FROM hogetable WHERE logdatetime = @testvalue2 OR @testvalue2 IS NULL
```

But,this SQL raises an exception in Npgsql 4 and 6
```
SELECT timestampcol FROM hogetable WHERE @testvalue2 IS NULL OR logdatetime = @testvalue2
```

Am I right in thinking that this is not a Dapper problem, but a Npgsql or Postgresql problem (or specification)?

**Comment by roji** [comment]
I indeed don't see this as Dapper-related in any way - see especially my last comment above on how this could happen to any type where DbType isn't set explicitly, not just DateTime. You could see this as a PostgreSQL problem, but I suspect you'd be told it's working as designed. I also believe Npgsql is behaving correctly here, and can't do much else to help you out.

If you can't change the SQL, you can still use Dapper's API for setting the DbType - that seems like a reasonable solution here.

**Comment by hkobayas014** [comment]
@roji Thank you very much for your detailed explanation and proposed solution. Based on the results of your answer, I will consider what I can do. Thank you.

**Comment by chrbkr** [comment]
I just stumbled across this issue. I doubt that the issue is in PostgreSQL: the problem seems to be specific to nullable DateTime - a null string works just fine:
```sql
SELECT *
FROM person p
WHERE (@lastName IS NULL OR p.lastname = @lastName)             -- works
  AND (@dateOfBirth IS NULL OR p.dateofbirth = @dateOfBirth)    -- fails
```
