### ISSUE TITLE
Same query returns different results on the same dataset (non-idempotent behaviour)

### ISSUE THREAD

**Issue by seoriy** [DapperLib/Dapper#1752]
I've faced with strange behavior of one of my SQL query - it is not idempotent. On same datasets (which is not changed by anyone else), with the same SQL query text and the same parameters it returns different results for several executions followed with interval in a few seconds (but not each time - few of them has same results) I've run such experiments many times for a day. Also, I've run the the same query with the same parameters in MS SQL Server Management Studio and it works as expected - returns the same resultset each time I run the query.  So I'm pretty sure, that it is not related to multiple user work in shared database. SQL query is quite heavy and contains aggregations, ordering, grouping and nested sub-queries and pagination, but contains nothing, which may return rows in a random order. 
I use Dapper v2.0.123, through DB connections created via EF Core 3.1.22, with Microsoft.EntityFrameworkCore.SqlServer data provider (SQL Server 12.0 hosted in Azure). 
Entity type is a flat POCO object. 
Actual code snippet:
```
var connection = DbContext.Database.GetDbConnection();
connection.Close(); // this doesn't helps
return connection.Query<TEntity>(new CommandDefinition(
    sql,
    parameters,
    commandType: CommandType.Text,  // this doesn't helps too
    flags: CommandFlags.NoCache));  // this doesn't helps as well
```
Unfortunately, I can't provide more details and exact SQL query because of NDA.
Did I missed something? Any ideas, what could help to make Dapper works in a proper way?

**Comment by mgravell** [comment]
Dapper doesn't choose what data to return - literally all it does is simplify the ADO.NET API (well, except for some magic with `in @vals` and `{=val}`, but that's a bit niche)

Not managing to repro it in SSMS does *not* mean that it isn't the server doing this. Random suggestions just off the top of my head:

1. your query genuinely is non-deterministic; note in particular that set operations are unordered unless explicitly specified, and while the server might often make the same decisions - it doesn't have to, especially when parallelism is involved
2. anything involving nolock or similar isolation levels; you can get double-reads, non-repeatable reads, etc
3. note that the default SET options in SSMS are not the same as the SET options in .NET, and this can cause a few minor variations; I can't remember which options, right now; this can be especially painful when used with persisted+indexed calculated columns, as incompatible SET options can mean the precalculated value is ignored
4. SET options (especially isolation levels) that are changed explicitly in your application's code; fun fact: the isolation level *doesn't get reset* when a pooled connection is recycled (and possibly s few option options); this means that if your code sets options *sometimes*, you can end up with different connections in the pool having different options - so running the *exact same code* can have different results, simply depending on which connection you were handed, which is outside of your control

And that's without even applying much thought, off the top of my head.

Note: none of these relate to Dapper!

Now: I am absolutely open to investigating and helping with some scenario where Dapper can be shown to be a genuine factor, but I'd need a repro rather than just a rumour.

**Comment by seoriy** [comment]
@mgravell, thank you very much for your quick response! You was right, it is not related to Dapper. The problem was in ordering by date field - when several records has the same date SQL Server returned them in random order. So just adding second sort order by Id fixed the issue. Sorry for bothering you!
