### ISSUE TITLE
Update to supported Target Frameworks?

### ISSUE THREAD

**Issue by mich-winkel** [DapperLib/Dapper#1792]
Is there a plan to update the target frameworks and dependencies to .NET 6 and .NET 4.6.2?  We are being denied the ability to use Dapper due to it targeting unsupported frameworks.  Thank you.

**Comment by mgravell** [comment]
Both should simply work. Net462 should pick up the net461 build, and net6.0 should pick up the net5.0 build.

What exactly are you seeing that says you can't use it?

**Comment by mich-winkel** [comment]
Since the dependencies are on non-supported frameworks (net461 and net5.0), we are no longer allowed to use Dapper in government systems.
As far as our team is concerned, Dapper works great in our systems and we want to continue using it, but the government it group has disallowed use.

Thank you for responding.

Michelle

**Comment by mich-winkel** [comment]
My question first of all is what I am proposing on the radar for your team.
What I am proposing is to change the Target Frameworks in the csproj files from .net461 to .net462 or higher and net5.0 to net6.0:
    <TargetFrameworks>net461;netstandard2.0;net5.0</TargetFrameworks>

**Comment by mgravell** [comment]
K, but: that literally doesn't change anything. The IL will be identical in those cases. Changing TFMs is useful to gain access to later APIs, but if we target net461, but you use net 462: you will be running 100% identical IL to if we targeted net462. The only difference is: we'd cut off some users.

Likewise, we could switch net5.0 to net6.0, or add both - but it would make absolutely no difference to you if you're already using net6.0 (unless.we make use of some net6.0 only features).

My point is: whoever is providing this guidance is... questionable. In addition, since net5.0 is the LTS build, I'm not dropping net5.0 any time soon - it will outlive net6.0 IIRC.

The fact that we allow lower frameworks doesn't impact you *if you're not using those frameworks*.

**Comment by mich-winkel** [comment]
Thank you for your response.  I will use your last comment to argue against the ban of using this wonderful tool.  Your response really helped me out and I will close this issue.

**Comment by mgravell** [comment]
Note: it isn't a *massive* problem to add TFMs - although it does increase package size a bit. Adding net6.0, for example, wouldn't be impossible.
