### ISSUE TITLE
Dapper dependency not loading. File not found.

### ISSUE THREAD

**Issue by mrobert09** [DapperLib/Dapper#1961]
I am having this same issue as seen here: https://github.com/DapperLib/Dapper/issues/1617 but unfortunately this issue was closed with no comment. Nothing I can find online seems to help. I am following along a C# tutorial but modifying it to fit my own project ideas: https://www.youtube.com/watch?v=wfWxdh-_k_4

When I connect Dapper to my project's form (starting around 5:54:00 in the tutorial) I get to the exact error GZI89 was having. For reference, I am on a basically fresh install of VS2022, this is the only project I've opened on this install, and this is the only NuGet package I've installed. Any help would be appreciated in fixing this issue.

This is the error received:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'`

**Comment by mgravell** [comment]
I couldn't see anything Dapper related at the relevant time. Can you narrow it down? It *should* be as simple as just adding the library - using the IDE's NuGet package manager, or any of the ways listed here: https://www.nuget.org/packages/Dapper/ - what type of project is this (console, winform, etc), and what framework are you targeting (net7.0, .net framework 4.8, etc)?

Your csproj should end up with something like `<PackageReference Include="Dapper" Version="2.0.151" />`

also, are you using any additional Dapper-esque tools? what *other* relevant packages are you referencing (in addition to simply "Dapper")?

**Comment by mrobert09** [comment]
He actually does the Dapper NuGet package install at around 5:52:00, right before the timestamp I gave. Then he goes on to setup a connection string and such.

Solution: Windows Form Application that uses two projects, one that is a Class Library and one that is a Windows Form. I have attempted to add the Dapper NuGet package initially to just the library, as the tutorial showed, but then also tried adding it to the window form and then the solution itself (which just added it to both projects from what I can tell).

Framework: The class library is targeting .NET Framework 4.8.1, the Windows Form is targeting .NET 7.0. I'm not even sure how those ended up different or if that is normal. I pretty much just used the recommended settings when starting these two projects.

.csproj has these lines near the end that mention Dapper:
`<ItemGroup>
    <Reference Include="Dapper, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Dapper.2.0.151\lib\net461\Dapper.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>`

**Comment by mgravell** [comment]
Right; so: .net framework (any version) and .net 7 are *wildly* incompatible. That's not a supported pairing, if either of those is meant to talk to the other. That could be a large part of the problem here. I'm also surprised that you have a hint path at all here - I'm guessing that is in the .net framework project? Hint paths are an older build tools technology that predates SDK-style projects.

It is hard to unpick what is going on here without seeing the projects in front of me, but: it sounds very much like this is a project file issue.

You have reminded me to try to cover old-style csproj in the upcoming book, however!

I think you should try to figure out whether you're meaning to target .net framework or .net 7 - they are completely different things - and fix or recreate whichever of the projects is misconfigured. Note that changing the .net 7 one to target .net framework is probably trivial - you *should* just need to tweak the `<Target framework>` in the csproj file to `net481` instead of `net7.0`

**Comment by mrobert09** [comment]
Thank you so much! That fixed the issue. Now sure how that happened.

**Comment by mgravell** [comment]
Just for my "things to remember for future occurrences" - what did you change? The target framework of the library?

If so, I might add this to the set of analyzers in DapperAOT...

**Comment by mrobert09** [comment]
Unfortunately, I went about fixing it in all the wrong ways. Originally I wanted to try to make it .NET 7.0, so I turned my Library into 7.0 by just recreating it and moving the .cs files over. I realized, however, the 7.0 does things differently so I wouldn't be able to follow along with the tutorial how I wanted, so I then recreated the whole thing in .NET Framework and had to spend an hour just squashing bugs.

That's what panicking will do to you, haha. There was probably a simpler way to move things over but oh well.
