### ISSUE TITLE
schema as parameter

### ISSUE THREAD

**Issue by lioror** [DapperLib/Dapper#2000]
Hi,
We have a lot of schemas in our db's, different schema per tenant.
Is there a way to parameterize the schema using dapper?

**Comment by mgravell** [comment]
Before we can ask whether *Dapper* can do this, we need to ask whether *any database* can do this, and usually the answer is a resounding "no". Object names (including the schema and/or db aspect) cannot usually be parameterized. Performing string replacement is a dangerous game that risks SQLI, so we tend to advocate against that - plus it would be "allocatey".

I *have* seen this done using the connection string, however; if you have a schema per tenant, you might also have a SQL login per tenant, and associate each SQL login with a different default schema. Then *your code* doesn't change at all, and neither does the query - but when connection A using connection-string X runs `"select * from Orders"` they get different results than when connection B using connection-string Y runs `"select * from Orders"`, because they're not the same default schema - one is implicitly "select * from schema_a.Orders", the other is "select * from schema_b.Orders". In this scenario I would recommend *not* having a `dbo.Orders`, to avoid confusion. This also prevents the risk of cross-talk between tenants, because user A *should only have access to the tables of schema_a*, etc - and note that this isn't a 100% fix - you can't use table-oriented UDFs, for example, since UDFs need to be schema-qualified (it would work for scalar UDFs that don't involve schema-related tables, though (such UDFs probably *should* be in a dbo schema).

**Comment by lioror** [comment]
@mgravell thanks for your answer.
We considered this approach, create a user per schema, but this has it's challenges, like we have thousands of schemas and don't want to manage all those users, let alone there might be a limit on the amount of users for a db.

So, our current approach is, replacing the schema in the sql string.
But we run to a memory issue, and found that dapper caches the sql string.
So, if for example a service does 3 different sql queries, it is stored 3 x number of schemas in memory.
Is there a way to clear this cache, or not cache it at all?

**Comment by mgravell** [comment]
1. Dapper.AOT - https://aot.dapperlib.dev/gettingstarted.html - but note that this is brand new and doesn't support all Dapper scenarios
2. Use CommandDefinition and pass in CommandFlags.NoCache

The first will be much, much more efficient - the second will offer more API compatibility
