### ISSUE TITLE
QueryMultiple in mono

### ISSUE THREAD

**Issue by ekgurney14** [DapperLib/Dapper#470]
Attempting to use dapper in a mono application using the QueryMultiple API.  It appears the the results are skipping every other resultset.  When I run under MS.Net all my results get read fine, but when I run with Mono.Net, I get a 'reader has been disposed error'.
Removing the CommandBehavior.SequentialAccess in the ExecuteReader seems to fix the problem (in a sample app anyway), but not sure of the implications...  Obviously this seems to be an issue with mono, but thought there might be a dapper specific solutions to the problem.

Thanks,
Eric

**Comment by mgravell** [comment]
I think this is the second report of this. If this is fixed by removing the
sequential access hint, then my guess would be a provider bug, but: wow
that's weird! I need to dust off my mono tools and get onto this. As it
happens, we already have most of the code to disable the optimisation
hints. It doesn't touch sequential access yet, though. Useful to know that
this might be a useful thing to look at!

**Comment by ekgurney14** [comment]
Definitely think it is a provider bug, I was able to reproduce using straight ADO with that flag set.  I just thought - if that flag isn't necessary...

thanks,
Eric

**Comment by mgravell** [comment]
No optimizations are strictly *necessary*, but working hard to try to
achieve great performance with minimal effort is *what dapper does*.

It definitely needs fixing. I need to update my mono setup.

**Comment by NickCraver** [comment]
I can't find the issue right now, but this was eventually fixed in the underlying provider - closing out to cleanup here.
