### ISSUE TITLE
choose any not-null item of param list to lookup dbtype,instead of the first item

### ISSUE THREAD

**Issue by hiwjcn** [DapperLib/Dapper#816]
https://github.com/StackExchange/Dapper/blob/610d8f65bcf1d72dbe083305b6cb018ef89a5126/Dapper/SqlMapper.cs#L2000

choose any not-null item of param list to lookup dbtype,instead of the first item

**Comment by mgravell** [comment]
That's something that *could* be improved - although it would require tracking how many parameters with `null` values we didn't add because we didn't know the type, and we'd need to think about what to do if they are *all* `null` - but first I'd like to understand the scenario where it is *necessary and useful* to do this... because *as I understand it*, most databases aren't going to match on a `null` *anyway* in this usage. Do you have a concrete example where this would be desirable?

**Comment by NickCraver** [comment]
Without a use case, closing this one out.
