### ISSUE TITLE
Type Flattening for query parameters

### ISSUE THREAD

**Issue by turbo** [DapperLib/Dapper#923]
FYI: https://stackoverflow.com/questions/48254109/dapper-doesnt-read-values-from-base-type-fields

Either:

- TF is supposed to happen, in which case this is a bug
- it's not, in which case the error should IMO be more helpful

**Comment by NickCraver** [comment]
Posted an answer on Stack Overflow - the issue is fields vs. properties, but the error message is coming from your RDBMS there, not Dapper. I'm not sure there's much we can reasonably do to improve this - catching and improving that exception would add quite a bit of complication. Given we've had few reports of the confusion, I'd lean towards not making any changes there.
